import Head from "next/head";
import styles from "../styles/Home.module.css";
import { MyButton } from "../components/Button/MyButton/MyButton";
import { TomatoButton } from "../components/Button/TomatoButton/TomatoButton";
import { MyInput } from "../components/Input/MyInput/MyInput";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Krisana Next app!</a>
        </h1>
        <p className={styles.description}>
          Test deploy next app with github action
        </p>
        <MyButton />
        MyButton
        <TomatoButton />
        TomatoButton
        <MyInput
          defaultValue="@probablyup"
          type="text"
          topValue={24}
          bottomValue={24}
          inputColor={"palevioletred"}
        />
        <MyInput
          defaultValue="@geelen"
          type="text"
          topValue={20}
          bottomValue={20}
          inputColor={"red"}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
